### ISSUE TITLE
Issue of modularity calculation

### ISSUE THREAD

**Issue by Christina2333** [neil-justice/louvain#18]
Hi, 
I am confused about the formula of modularity in the code, 
In general, the definition of modularity in louvain is as follows: 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/26264755/228787160-79d0b6d3-0542-4bf9-999a-304e1de64610.png">
Aij represents the weight between node i and node j, ki represents the degree of node i. 

The corresponding code is as follows:
https://github.com/neil-justice/louvain/blob/master/src/main/java/com/github/neiljustice/louvain/graph/Graph.java#L201
which looks very different from the formula. `totDegree` means the sum of degrees within a community, `intDegree` means the sum of weights within a community. `m2` means weight of all edges in 
https://github.com/neil-justice/louvain/blob/master/src/main/java/com/github/neiljustice/louvain/graph/GraphBuilder.java#L207

The following code also confuses me:
https://github.com/neil-justice/louvain/blob/master/src/main/java/com/github/neiljustice/louvain/graph/GraphBuilder.java#L206 
i think it should be: `degrees[n1] += 1;`

Looking forward to your reply.

**Comment by neil-justice** [comment]
Hello,

It's been many years since I wrote this and I don't know the code well at all any more, sorry. I will try and answer your questions.

re: modularity definition - if you read section 2 of [this paper](https://arxiv.org/pdf/cond-mat/0408187.pdf) you will see how the algorithm for modularity used here is derived from the one you have.

> The following code also confuses me:
https://github.com/neil-justice/louvain/blob/master/src/main/java/com/github/neiljustice/louvain/graph/GraphBuilder.java#L206
i think it should be: degrees[n1] += 1;

I think this is correct as it is currently - maybe it should be called `weightedDegree`, but I believe for the Louvain algorithm to function properly it needs to use the weighted degree rather than just the degree, as the hierarchical community detection relies on turning the communities from the previous layer into a weighted graph (where the weights are the sum of all weights of all edges between any nodes in the 2 communities) on which to run the community detection again.

I Hope that helps.

**Comment by Christina2333** [comment]
Thanks for your answer!  In fact, I am grouping the weighted graph using louvain, but the effect is not ideal. I will look at the reason later.
